services:
  mysql:
    image: mysql:8.0
    container_name: mysql-forum
    restart: always
    environment:
      MYSQL_DATABASE: forumdb
      MYSQL_USER: forum
      MYSQL_PASSWORD: forum12
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3806:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - forum-net

  postgres:
    image: postgres:16
    container_name: postgres-keycloak
    environment:
      POSTGRES_DB: keycloakdb
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak12
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - forum-net

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.3
    container_name: keycloak-forum
    command:
      - start-dev
      - --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: ofk12
      KC_REALM_NAME: markets-forum
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloakdb
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak12
      KC_PROXY: edge
    volumes:
      - ./keycloak/realm:/opt/keycloak/data/import
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - forum-net

  api:
    build: ./api
    container_name: api-forum
    ports:
      - "8081:8080"
    depends_on:
      - mysql
      - keycloak
    networks:
      - forum-net

  frontend:
    build: ./frontend
    container_name: frontend-forum
    ports:
      - "80:80"
    depends_on:
      - api
      - keycloak
    networks:
      - forum-net

volumes:
  mysqldata: {}
  pgdata: {}

networks:
  forum-net:
    driver: bridge
