server:
  port: 8180

spring:
  datasource:
    url: jdbc:mysql://localhost:3806/forumdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: forum
    password: forum12

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/markets-forum

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

file:
  upload-dir: uploads/profile-photos

app:
  base-url: http://localhost:8180